# The following line is needed
# when running the example site
# from a subdir of the theme
themesDir = "../../"

title = "not-much demo"
theme = "not-much"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "Sample custom notice © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
showPostsSummary = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2
	
  [[menu.main]]
    identifier = "publications"
    name = "publications"
    title = "publications"
    url = "/publications"
    weight = 3
  
  [[menu.main]]
    identifier = "cv"
    name = "cv"
    title = "CV"
    #url = "/cv"
	url = "/doc/Iori_CV_March2025.pdf"
    weight = 4
	
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact"
    weight = 5
	
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/martina-iori"
    weight = 6